- name: Health Check
  hosts: all
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: IPV4
      debug:
        msg: "{{ ansible_facts['default_ipv4']['address'] }}"

    - name: Get package facts
      package_facts:
        manager: auto

    - name: Version sudo
      debug:
        msg: "{{ ansible_facts.packages['sudo'][0].version }}"
#      when: "'sudo' in ansible_facts.packages"

    - name: Sortie vers fichier
      lineinfile:
        path: /tmp/toto.txt
        state: present
        line: "{{ ansible_hostname }} {{ ansible_facts['default_ipv4']['address'] }}"
      
