- name: Health Check
  hosts: all
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: IPV4
      debug:
        msg: "{{ ansible_facts['default_ipv4']['address'] }}"

    - name: Get package facts
      package_facts:
        manager: auto

    - name: Version sudo
      debug:
        msg: "ansible_hostname={{ ansible_hostname }} {{ ansible_facts.packages['sudo'][0].version }}"

   
